version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://localhost:27017/myrole # Replace with your MongoDB URI
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app

volumes:
  mongo-data:
